### ISSUE TITLE
gui becomes blank when clicking on a target. 

### ISSUE THREAD

**Issue by SylvanFranklin** [vldmrkl/airdrop-cli#14]
![Screenshot 2024-03-24 at 11 22 02](https://github.com/vldmrkl/airdrop-cli/assets/103258778/d0ecff5b-2480-4f0f-8d26-ef2a03fe1738)

![Screenshot 2024-03-24 at 11 21 43](https://github.com/vldmrkl/airdrop-cli/assets/103258778/8d010220-20ea-4c87-b4de-34a961fc2c8e)

After clicking on any button the native dialog loses all functionality.

**Comment by occludedpixel** [comment]
@SylvanFranklin did you install using `brew install --HEAD airdrop-cli` ?

**Comment by SylvanFranklin** [comment]
works with head install.
