### ISSUE TITLE
Can't install from brew

### ISSUE THREAD

**Issue by theipol** [vldmrkl/airdrop-cli#16]
I tried to install via brew and get that:

Warning: No available formula with the name "airdrop-cli". Did you mean arduino-cli?
==> Searching for similarly named formulae and casks...
==> Formulae
arduino-cli

To install arduino-cli, run:
  brew install arduino-cli

==> Casks
airdroid

To install airdroid, run:
  brew install --cask airdroid

It is necessary?

**Comment by derhuerst** [comment]
The readme explains that, before running `brew install airdrop-cli`, you need to run `brew tap vldmrkl/formulae`.

**Comment by theipol** [comment]
Yes, I did it!
The thing is, I needed to install XCode before running it, and then it started working fine!
