### ISSUE TITLE
can't install on m1 macbook pro

### ISSUE THREAD

**Issue by mickmcq** [vldmrkl/airdrop-cli#8]
Works fine on my intel machine but on two different m1 macbook pros I get an error message saying I don't have permission on /Users/mm223266/Library/org.swift.swiftpm so I created that directory and chowned to mm223266 and chmod to 777. Still same error. So I created subdirectories security and configuration and gave them the same permissions. Still same error. Log attached.

[01dotswift.txt](https://github.com/vldmrkl/airdrop-cli/files/9559339/01dotswift.txt)

**Comment by LudusLight** [comment]
I'm experiencing this as well on an m2

**Comment by vldmrkl** [comment]
@mickmcq , @LudusLight please try following [Building from source](https://github.com/vldmrkl/airdrop-cli#building-from-source) section.
Hope this helps.

**Comment by mickmcq** [comment]
It worked! But I had to first say

```bash
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
```

to avoid an error message `no such module: "PackageDescription"` that resulted because xcode-select was pointing to the Xcode cli tools.
